ARG STACTOOLS_VERSION=latest
FROM ghcr.io/stac-utils/stactools:${STACTOOLS_VERSION}-dev

WORKDIR /opt/stactools-lila-hkh-glacier

# For caching purposes, install dependencies but remove the actual package
COPY pyproject.toml requirements-dev.txt setup.cfg ./
COPY src/stactools/lila_hkh_glacier/__init__.py src/stactools/lila_hkh_glacier/
RUN pip install -r requirements-dev.txt \
    && pip install . \
    && rm -r /opt/conda/lib/python3.8/site-packages/stactools/lila_hkh_glacier

COPY . ./
RUN pip install -e .
